version: '3'

services:
  broker:
    build: ./rabbitmq
    networks:
      - internal

  result_backend:
    build: ./result_backend
    networks:
      - internal

  worker:
    build: ./worker
    command: tail -F anything
    volumes:
      - ./proj:/home/danh/celery/proj
    networks:
      - internal

networks:
  internal:
    name: celery-internal
